"""
Django settings for Glossa project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import shutil
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-amwm)3p($3ap(efn&d934mz@rz)tdnc7g=7+oz0ycem58=t&#!",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in {"1", "true", "yes", "on"}
VERCEL = os.environ.get("VERCEL", "").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = {
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if host.strip()
}

render_external_hostname = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if render_external_hostname:
    ALLOWED_HOSTS.add(render_external_hostname)

for vercel_host in (
    os.environ.get("VERCEL_URL", "").strip(),
    os.environ.get("VERCEL_PROJECT_PRODUCTION_URL", "").strip(),
):
    if vercel_host:
        ALLOWED_HOSTS.add(vercel_host.removeprefix("https://").removeprefix("http://"))

ALLOWED_HOSTS = sorted(ALLOWED_HOSTS)

CSRF_TRUSTED_ORIGINS = {
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
}

render_external_url = os.environ.get("RENDER_EXTERNAL_URL", "").strip()
if render_external_url:
    CSRF_TRUSTED_ORIGINS.add(render_external_url)

for vercel_host in (
    os.environ.get("VERCEL_URL", "").strip(),
    os.environ.get("VERCEL_PROJECT_PRODUCTION_URL", "").strip(),
):
    if vercel_host:
        vercel_host = vercel_host.removeprefix("https://").removeprefix("http://")
        CSRF_TRUSTED_ORIGINS.add(f"https://{vercel_host}")

CSRF_TRUSTED_ORIGINS = sorted(CSRF_TRUSTED_ORIGINS)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "users",
    "dictionary",
    "quiz",
    "friends",
    "pages",
    "wordofday",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Glossa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Glossa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

database_url = (
    os.environ.get("DATABASE_URL")
    or os.environ.get("POSTGRES_URL_NON_POOLING")
    or os.environ.get("POSTGRES_URL")
)

if database_url:
    DATABASES = {
        "default": dj_database_url.parse(
            database_url,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    sqlite_path = BASE_DIR / "db.sqlite3"

    if VERCEL:
        # Vercel's deployment filesystem is read-only. Copy the bundled
        # SQLite database into /tmp so forms, sessions, and demo data can
        # still work when no external Postgres database is configured yet.
        sqlite_tmp_path = Path("/tmp/db.sqlite3")
        if not sqlite_tmp_path.exists() and sqlite_path.exists():
            shutil.copy2(sqlite_path, sqlite_tmp_path)
        sqlite_path = sqlite_tmp_path

    DATABASES = {
        "default": dj_database_url.parse(
            f"sqlite:///{sqlite_path}",
            conn_max_age=600,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
LOGIN_URL = "/users/login/"
LOGOUT_REDIRECT_URL = 'landing'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
