# Generated by Django 6.0 on 2025-12-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language_chocies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_lang',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone_Number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
