# Generated by Django 6.0 on 2025-12-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofday', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordOfTheDay',
        ),
    ]
